{% set name = "alabaster" %}
{% set version = "0.7.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alabaster-{{ version }}.tar.gz
  sha256: c84aa888cf8ebce113ef3fbbd63092aeb8cff9e6274ed2f27d014ca16f258948

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6


test:
  imports:
    - alabaster
  requires:
    - pip
  commands:
    - pip check
    - python -c "import alabaster; print(alabaster.get_path())"

about:
  home: http://www.sphinx-doc.org/en/stable/index.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Configurable, Python 2+3 compatible Sphinx theme.
  description: |
    Alabaster is a visually clean, responsive, and configurable Sphinx
    theme. It is sidebar-enabled and easy to install/use as a Python
    package. As of Sphinx 1.3, Alabaster is selected as the default
    theme for Sphinx.
  doc_url: https://anaconda.org/anaconda/alabaster
  dev_url: https://github.com/bitprophet/alabaster

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - ocefpaf
