{% set version = "0.7.13" %}

package:
  name: alabaster
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/alabaster/alabaster-{{ version }}.tar.gz
  sha256: a27a4a084d5e690e16e01e03ad2b2e552c61a65469419b907243193de1a84ae2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - alabaster
  commands:
    - python -c "import alabaster; print(alabaster.get_path())"

about:
  home: http://www.sphinx-doc.org/en/stable/index.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Configurable, Python 2+3 compatible Sphinx theme.
  description: |
    Alabaster is a visually clean, responsive, and configurable Sphinx
    theme. It is sidebar-enabled and easy to install/use as a Python
    package. As of Sphinx 1.3, Alabaster is selected as the default
    theme for Sphinx.
  doc_url: https://anaconda.org/anaconda/alabaster
  dev_url: https://github.com/bitprophet/alabaster

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - ocefpaf
