{% set name = "alabaster" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alabaster-{{ version }}.tar.gz
  sha256: c00dca57bca26fa62a6d7d0a9fcce65f3e026e9bfe33e9c538fd3fbb2144fd9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.7
    - pip
  run:
    - python >={{ python_min }}


test:
  imports:
    - alabaster
    - alabaster.support
  requires:
    - pip
    - pygments
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import alabaster; print(alabaster.get_path())"

about:
  home: https://alabaster.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: A light, configurable Sphinx theme
  description: |
    Alabaster is a visually clean, responsive, and configurable Sphinx
    theme, and the default theme for Sphinx.
  doc_url: https://alabaster.readthedocs.io/
  dev_url: https://github.com/sphinx-doc/alabaster

extra:
  recipe-maintainers:
    - AA-Turner
    - conda-forge/sphinx
    - msarahan
    - r-jain1
    - ocefpaf
