{% set name = "alabaster" %}
{% set version = "0.7.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alabaster-{{ version }}.tar.gz
  sha256: c84aa888cf8ebce113ef3fbbd63092aeb8cff9e6274ed2f27d014ca16f258948

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9


test:
  imports:
    - alabaster
  requires:
    - pip
  commands:
    - pip check
    - python -c "import alabaster; print(alabaster.get_path())"

about:
  home: https://alabaster.readthedocs.io/en/latest/index.html
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A light, configurable Sphinx theme
  description: |
    Alabaster is a visually clean, responsive, and configurable Sphinx
    theme, and the default theme for Sphinx.
  doc_url: https://anaconda.org/anaconda/alabaster
  dev_url: https://github.com/sphinx-doc/alabaster

extra:
  recipe-maintainers:
    - AA-Turner
    - conda-forge/sphinx
    - msarahan
    - r-jain1
    - ocefpaf
