travis:
  secure:
    BINSTAR_TOKEN: IoN69d7528WrHfSc2rqaJYTHleyCukK7TkfOta8MwDEAZvvRWwEg6WiEV+LLGXZQvAwHrsWTa0eRgytl8503yZHEqfdiGnb3dau7UJv5xSLv07VaMSUJSA8ibNbKUOks1UIiZkbYNlnXtO7OyyHgUHkqlcpn5dvAubZjMRSBvCbIl3zlWCpyhk/ZSErgTW2/jQojZo+vmzt3gXAqrLvWov9cPXrNbrvk2gpoKkwBpO3yzvAFgzOyjh3Vm2OBFWyUllZwnGZlv0Bx127ZfDO+vHUMVT6+yNAo351Lo1y8I4w7SJRjR+bdVLnnqrmemuT1Oa1B9vwoMXTeS18Hrj7RrOB8DTp8LsxFH0njOtg8kuY+rB5E2m08pxJNzcqEFzT46lcCsejLJOkRTTezDQiAK+4tN8pNrDotqStcCr/fPnoOkEWzJq6YBcwXtxMyoEOAEJoYp1CbAVIHNF7+pGEcmFUvqoPblF2hPqUMktk0pOhafT/6a6HN5Qe94gLQY/Ro3UVlZIXkLVS404499jxnKRyFQGH03mw8aegxXNShNoiBNiMLJOe4DDJzK/UyRNmXqTjoel8vMwGrJ9t3NkoLX9EcGf6Eq57xechOW1kqrwfAEJpO9cnbUjX5GjpMmZ5+9P3gHQUqcPTADx31a7LKr4S+2MciX5d3l47mDwNKgCM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
